CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    tg_user_id BIGINT,
    student_group_name VARCHAR(15),
    registrationDate DATETIME
);

CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT IDENTITY PRIMARY KEY,
    tg_group_id BIGINT,
    tg_group_name VARCHAR(255)
);